#!/usr/bin/env python3
"""Derive a train/dev-only rescue map from grounding evaluation output.

This script builds deterministic overrides from misses observed in an eval JSON
(e.g., ground_truth_vector_eval.json) while filtering rows to a chosen split
(default: dev_rows) from split_v3_all_tables.json.

Leakage control:
- Only rows in the chosen split are used to derive overrides.
- By default, only unambiguous term+role pairs are emitted
  (all observed misses agree on one gold concept_id).
"""

from __future__ import annotations

import argparse
import json
from collections import defaultdict
from dataclasses import dataclass
from pathlib import Path
from typing import Dict, Iterable, List, Optional, Set, Tuple


@dataclass
class Candidate:
    term: str
    role: str
    gold_ids: Set[str]
    miss_count: int
    rows: Set[str]


def _load_json(path: Path) -> dict:
    return json.loads(path.read_text(encoding="utf-8"))


def _resolve_split_rows(split_payload: dict, split_name: str) -> Set[str]:
    aliases: Dict[str, List[str]] = {
        "dev": ["dev", "dev_rows"],
        "locked_test": ["locked_test", "locked_test_rows"],
    }
    keys = aliases.get(split_name, [split_name])
    for key in keys:
        values = split_payload.get(key)
        if isinstance(values, list) and values:
            return {str(v) for v in values}
    list_keys = sorted(k for k, v in split_payload.items() if isinstance(v, list))
    raise ValueError(
        f"No rows found for split '{split_name}'. Checked keys={keys}; "
        f"available list-keys={list_keys}"
    )


def _split_row_to_eval_row_id(split_row: str) -> Optional[str]:
    # Expected forms:
    # - table22:row_02      -> t22_row_02
    # - table8:row_03       -> t8_row_03
    # - table17:t0_row_03   -> t0_row_03
    if ":" not in split_row:
        return None
    table_prefix, row_part = split_row.split(":", 1)
    table_prefix = table_prefix.strip().lower()
    row_part = row_part.strip()

    if table_prefix in {"table22", "table8"} and row_part.startswith("row_"):
        table_num = table_prefix.replace("table", "")
        return f"t{table_num}_{row_part}"

    if table_prefix == "table17" and row_part.startswith("t") and "_row_" in row_part:
        return row_part

    return None


def _collect_candidates(
    predictions: Iterable[dict],
    allowed_eval_rows: Set[str],
    min_miss_count: int,
    require_unambiguous: bool,
) -> List[Candidate]:
    grouped: Dict[Tuple[str, str], Candidate] = {}

    for row in predictions:
        if row.get("hit"):
            continue
        row_id = str(row.get("row_id") or "").strip()
        if row_id not in allowed_eval_rows:
            continue

        term = str(row.get("term") or "").strip()
        role = str(row.get("role") or "").strip()
        gold_id = str(row.get("gold_snomed_id") or "").strip()
        if not term or not role or not gold_id:
            continue

        key = (term.lower(), role.lower())
        existing = grouped.get(key)
        if existing is None:
            existing = Candidate(
                term=term,
                role=role,
                gold_ids=set(),
                miss_count=0,
                rows=set(),
            )
            grouped[key] = existing
        existing.gold_ids.add(gold_id)
        existing.miss_count += 1
        existing.rows.add(row_id)

    out: List[Candidate] = []
    for candidate in grouped.values():
        if candidate.miss_count < min_miss_count:
            continue
        if require_unambiguous and len(candidate.gold_ids) != 1:
            continue
        out.append(candidate)

    out.sort(key=lambda c: (-c.miss_count, c.role.lower(), c.term.lower()))
    return out


def _write_yaml(overrides: List[Candidate], output_path: Path) -> None:
    lines: List[str] = []
    lines.append("# Train/dev-derived deterministic rescue overrides.")
    lines.append("# Generated by scripts/derive_train_only_rescue_map.py")
    lines.append("# Do not add locked_test-derived entries.")
    lines.append("")
    lines.append("overrides:")

    if not overrides:
        lines.append("  []")
    else:
        for c in overrides:
            concept_id = sorted(c.gold_ids)[0]
            escaped_term = c.term.replace('"', '\\"')
            escaped_role = c.role.replace('"', '\\"')
            lines.append(f"  - term: \"{escaped_term}\"")
            lines.append(f"    role: \"{escaped_role}\"")
            lines.append(f"    concept_id: {concept_id}")
            lines.append("")

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text("\n".join(lines).rstrip() + "\n", encoding="utf-8")


def _write_report(
    report_path: Path,
    split_name: str,
    split_rows_count: int,
    allowed_eval_rows_count: int,
    derived: List[Candidate],
    dropped_ambiguous: List[Candidate],
    min_miss_count: int,
) -> None:
    payload = {
        "split_name": split_name,
        "split_rows_count": split_rows_count,
        "allowed_eval_rows_count": allowed_eval_rows_count,
        "min_miss_count": min_miss_count,
        "derived_count": len(derived),
        "derived": [
            {
                "term": c.term,
                "role": c.role,
                "concept_id": sorted(c.gold_ids)[0],
                "miss_count": c.miss_count,
                "rows": sorted(c.rows),
            }
            for c in derived
        ],
        "dropped_ambiguous": [
            {
                "term": c.term,
                "role": c.role,
                "gold_ids": sorted(c.gold_ids),
                "miss_count": c.miss_count,
                "rows": sorted(c.rows),
            }
            for c in dropped_ambiguous
        ],
    }
    report_path.parent.mkdir(parents=True, exist_ok=True)
    report_path.write_text(json.dumps(payload, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--eval-json", type=Path, required=True)
    parser.add_argument("--split-file", type=Path, required=True)
    parser.add_argument("--split-name", default="dev")
    parser.add_argument(
        "--output-map",
        type=Path,
        default=Path("config/cardio_graph_core/grounding_rescue_map_train_only.yaml"),
    )
    parser.add_argument(
        "--output-report",
        type=Path,
        default=Path("docs/generated/grounding/train_rescue_derivation_report.json"),
    )
    parser.add_argument("--min-miss-count", type=int, default=1)
    parser.add_argument(
        "--allow-ambiguous",
        action="store_true",
        help="If set, include term+role entries even when multiple gold IDs were observed.",
    )
    args = parser.parse_args()

    eval_payload = _load_json(args.eval_json)
    predictions = eval_payload.get("predictions") or []
    if not isinstance(predictions, list):
        raise SystemExit("eval JSON has no 'predictions' list")

    split_payload = _load_json(args.split_file)
    split_rows = _resolve_split_rows(split_payload, args.split_name)
    allowed_eval_rows = {
        row_id
        for row_id in (_split_row_to_eval_row_id(item) for item in split_rows)
        if row_id
    }
    if not allowed_eval_rows:
        raise SystemExit(
            f"No compatible split rows could be mapped to eval row_id for split '{args.split_name}'"
        )

    all_candidates = _collect_candidates(
        predictions=predictions,
        allowed_eval_rows=allowed_eval_rows,
        min_miss_count=args.min_miss_count,
        require_unambiguous=False,
    )

    if args.allow_ambiguous:
        derived = all_candidates
        dropped_ambiguous: List[Candidate] = []
    else:
        derived = [c for c in all_candidates if len(c.gold_ids) == 1]
        dropped_ambiguous = [c for c in all_candidates if len(c.gold_ids) > 1]

    _write_yaml(derived, args.output_map)
    _write_report(
        report_path=args.output_report,
        split_name=args.split_name,
        split_rows_count=len(split_rows),
        allowed_eval_rows_count=len(allowed_eval_rows),
        derived=derived,
        dropped_ambiguous=dropped_ambiguous,
        min_miss_count=args.min_miss_count,
    )

    print(f"split_name={args.split_name}")
    print(f"split_rows={len(split_rows)}")
    print(f"allowed_eval_rows={len(allowed_eval_rows)}")
    print(f"derived_overrides={len(derived)}")
    print(f"dropped_ambiguous={len(dropped_ambiguous)}")
    print(f"output_map={args.output_map}")
    print(f"output_report={args.output_report}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
