"""
This script demonstrates the "Full Export/Import" approach for creating complete
snapshots of your Neo4j database using the APOC library.

---
What is the Full Export/Import (APOC) approach?
---
This method exports the entire database (or a selection) into a portable Cypher
script. This script contains all the `CREATE` statements for nodes, relationships,
indexes, and constraints. It's a reliable way to create a full, point-in-time
backup of your graph.

It's ideal for:
- Creating major versioned backups (e.g., 'v1.0', 'v2.0').
- Migrating the database to another server.
- Disaster recovery.

This method is slower than in-graph versioning for quick experiments but provides
a more complete and isolated backup.

---
How to use this approach in your project:
---
1.  **Export the Graph (Backup):**
    Run the `export_graph_to_file` function. This will connect to the database,
    call the `apoc.export.cypher.all` procedure, and stream the resulting Cypher
    commands into a local file (e.g., 'my_graph_backup.cypher').

2.  **Restore the Graph:**
    To restore the graph from a backup file, you have two main options:

    a) **Full Restore (Destructive):**
       First, completely clear the database by running `MATCH (n) DETACH DELETE n`.
       Then, run the `restore_graph_from_file` function, pointing it to your
       backup file. This will rebuild the graph from scratch.

    b) **Partial Restore (Non-Destructive):**
       If you want to add the data from the backup to the existing graph without
       deleting anything, simply run `restore_graph_from_file` on the live
       database. Note that this may create duplicate data if the nodes/relationships
       already exist.

This script provides functions to test the full export and restore cycle.
"""

import os

from neo4j import GraphDatabase, exceptions

# --- Configuration ---
# Update these with your database credentials
URI = "bolt://neo4j-dev2.internal:7687"
AUTH = ("neo4j", "KWCeoHhkJYAiFa3XTZZZLC77bHiZ5xzj")
# Define the default file path for the backup
DEFAULT_BACKUP_FILE = "neo4j_graph_backup.cypher"


def run_query(driver, query, **params):
    """A helper function to execute a Cypher query."""
    try:
        records, _, _ = driver.execute_query(query, **params)
        return records
    except Exception as e:
        # We print errors for schema operations (like index creation) as they are expected
        # during a restore, but we don't want to halt the process.
        if "EquivalentSchemaRuleAlreadyExists" in str(e):
            print(f"   [INFO] Schema object already exists. Skipping. (Error: {e})")
        else:
            print(f"   [ERROR] Query failed: {e}")
        return None


def export_graph_to_file(driver, file_path):
    """
    Exports the entire graph to a local Cypher script using APOC.

    This function connects to the database and uses `apoc.export.cypher.all` to
    generate `CREATE` statements for all nodes, relationships, and schema objects.
    The output is streamed directly to a local file.
    """
    print(f"\n1. Exporting graph to '{file_path}' using APOC...")
    # The query streams all data as Cypher statements.
    # `stream: true` and `format: 'plain'` are key for portability.
    query = """
    CALL apoc.export.cypher.all(null, {
        stream: true,
        format: 'plain',
        useOptimizations: {type: "UNWIND_BATCH", batchSize: 500}
    })
    YIELD cypherStatements
    RETURN cypherStatements
    """
    try:
        records, _, _ = driver.execute_query(query)
        with open(file_path, "w") as f:
            for record in records:
                f.write(record["cypherStatements"])
        print(f"   Graph successfully exported to {file_path}.")
        return True
    except Exception as e:
        print(f"   [FATAL] APOC export failed: {e}")
        print(
            "   Please ensure the APOC plugin is installed and enabled on the Neo4j server."
        )
        return False


def restore_graph_from_file(driver, file_path):
    """
    Restores a graph by executing the statements from a Cypher backup file.

    This function reads a Cypher script (generated by APOC) and executes each
    statement one by one. It's designed to handle large files and will print
    informational messages if it tries to re-create existing indexes or constraints.
    """
    print(f"\n2. Restoring graph from '{file_path}'...")
    try:
        with open(file_path, "r") as f:
            cypher_script = f.read()

        # The script is split into individual statements.
        statements = [
            stmt.strip() for stmt in cypher_script.split(";\n") if stmt.strip()
        ]

        if not statements:
            print("   [WARNING] Backup file is empty. Nothing to restore.")
            return True

        print(f"   Found {len(statements)} statements to execute.")
        for stmt in statements:
            # Skip shell-specific commands
            if not stmt.lower().startswith((":begin", ":commit")):
                run_query(driver, stmt)

        print("   Restore process completed.")
        return True
    except FileNotFoundError:
        print(f"   [FATAL] Backup file not found: '{file_path}'")
        return False
    except Exception as e:
        print(f"   [FATAL] An error occurred during restore: {e}")
        return False


# --- Helper functions for the demonstration ---


def clear_database(driver):
    """(For Demo Only) Clears the entire database."""
    print("\n--- (Demo) Clearing entire database for clean restore ---")
    run_query(driver, "MATCH (n) DETACH DELETE n")
    print("--- (Demo) Database cleared ---")


def verify_data_exists(driver):
    """(For Demo Only) Checks if any data exists in the graph."""
    print("\n--- (Demo) Verifying data restoration ---")
    records = run_query(driver, "MATCH (n) RETURN count(n) as count")
    if records and records[0]["count"] > 0:
        print(f"   Success! Found {records[0]['count']} nodes in the graph.")
    else:
        print("   Verification failed. No data found after restore.")


def main():
    """Main function to demonstrate the backup and restore workflow."""
    print("--- Full Graph Backup & Restore Demo (using APOC) ---")
    driver = None
    try:
        driver = GraphDatabase.driver(URI, auth=AUTH)
        driver.verify_connectivity()
        print("Connection to database successful.")

        # --- Workflow Demonstration ---
        # Step 1: Export the current state of the graph to a file.
        if export_graph_to_file(driver, DEFAULT_BACKUP_FILE):

            # Step 2 (Optional for Demo): Clear the database to simulate a restore
            # to a clean environment. In a real scenario, you might do this to
            # revert the database to the backup state.
            clear_database(driver)

            # Step 3: Restore the graph from the backup file.
            if restore_graph_from_file(driver, DEFAULT_BACKUP_FILE):
                # Step 4 (Optional for Demo): Verify that the data was restored.
                verify_data_exists(driver)

    except Exception as e:
        print(f"[FATAL] An unexpected error occurred: {e}")
    finally:
        if driver:
            driver.close()
        # Clean up the local backup file
        if os.path.exists(DEFAULT_BACKUP_FILE):
            os.remove(DEFAULT_BACKUP_FILE)
            print(f"\nCleaned up local backup file: '{DEFAULT_BACKUP_FILE}'")
        print("\n--- Demo Finished ---")


if __name__ == "__main__":
    main()
